* insert-shebang
  Insert shebang line automatically.
** Clone
   Clone this repository
   #+BEGIN_SRC shell
     git clone https://gitlab.com/psachin/insert-shebang.git
   #+END_SRC

** Install
*** Melpa-stable: [[http://stable.melpa.org/#/insert-shebang][file:http://stable.melpa.org/packages/insert-shebang-badge.svg]] [[http://marmalade-repo.org/packages/insert-shebang][Marmalade]]
    #+BEGIN_SRC emacs-lisp
      M-x package-install RET insert-shebang RET
    #+END_SRC

*** Manual install
     - Add directory containing =insert-shebang.el= file to =load-path= in your
       =~/.emacs= file. For example:
       #+BEGIN_SRC emacs-lisp
         (add-to-list 'load-path "/path/to/insert-shebang/")
       #+END_SRC

     - To load a package, add:
       #+BEGIN_SRC emacs-lisp
         (require 'insert-shebang)
       #+END_SRC

     - Optionally, run =make= to byte-compile the file.

** Customize
   Customize using:
   #+BEGIN_SRC emacs-lisp
     M-x customize-group RET insert-shebang RET
   #+END_SRC

*** Env Path
    Defines path to =env=. Default is =/usr/bin/env=.

*** File Types
    Defines file types.

*** Custom Headers
    *insert-shebang* can be extended to insert header for C, C++ and
    FORTRAN programs etc.

*** Ignore Extensions
    Set file types(using extensions) you want to ignore.

*** Ignored Filename
    Files ignored during the prompt are stored with their full-path
    in =~/.insert-shebang.log= file. Set to *nil* if you want to
    disable this feature.

    You can visit this log file using:
    #+BEGIN_SRC emacs-lisp
      M-x insert-shebang-open-log-buffer
    #+END_SRC

** Contribute
   - Feel free to send a [[https://docs.gitlab.com/ee/user/project/merge_requests/][Merge Request]]
   - Create new issues
   - Make sure to run tests before sending a Merge Request:
     #+BEGIN_SRC shell
       make test
     #+END_SRC

** License
   - See [[https://github.com/psachin/insert-shebang/blob/master/COPYING][COPYING]]
